export const SET_CURRENT_UPLOAD_PAGE = 'SET_CURRENT_UPLOAD_PAGE';
export const SET_APP_NAME = 'SET_APP_NAME';
export const SET_DESCRIPTION = 'SET_DESCRIPTION';
export const SET_APP_ID = 'SET_APP_ID';

export const ADD_MEDIA = 'ADD_MEDIA';

export const CLEAR_UPLOAD_SCREEN = 'CLEAR_UPLOAD_SCREEN';