export const UPDATE_SCREEN = 'UPDATE_SCREEN';
export const UPDATE_PASSCODE_ENTRY = 'UPDATE_PASSCODE_ENTRY';
export const UPDATE_LOCKED_STATUS = 'UPDATE_LOCKED_STATUS';
export const UPDATE_SOUND_STATUS = 'UPDATE_SOUND_STATUS';
export const UPDATE_VOLUME = 'UPDATE_VOLUME';

export const PLAY_AUDIO = 'PLAY_AUDIO';